// <auto-generated />
using ConfigurationWebShopDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfigurationWebShopDemo.Migrations.CompdatabaseDb
{
    [DbContext(typeof(CompdatabaseDbContext))]
    [Migration("20220317173602_AddCPUTableToDatabase")]
    partial class AddCPUTableToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConfigurationWebShopDemo.Models.CPU", b =>
                {
                    b.Property<int>("cpu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cpu_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("cpu_price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("cpu_id");

                    b.ToTable("CPU");
                });

            modelBuilder.Entity("ConfigurationWebShopDemo.Models.Configurations", b =>
                {
                    b.Property<int>("Configuration_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Computer_Case")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HDD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sound_Card")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WWAN_Card")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Configuration_Id");

                    b.ToTable("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
